name: proyecto-yesi-lab1
 
on:
 
  push:
    workflow_dispatch:
 
jobs:
 
  build:
   
    runs-on: ubuntu-latest
 
    steps:
 
      - name: Descarga repositorio
        uses: actions/checkout@v3
 
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} #force

      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@1.1.0
        with:
          project: 'final-lab-1'
          path: '.'
          format: 'HTML'
     
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports


      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
         
      - name: Build Docker
        run: |
          docker build --tag yesibeth/curso-devsecops:latest .

      - name: Execute Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'yesibeth/curso-devsecops:latest'
          format: 'table'
          #exit-code: 1

      - name: Push Docker
        run: | 
          docker push yesibeth/curso-devsecops:latest
          
  deploy:
    needs: build
    runs-on: self-hosted
    
    steps:
       - name: Pull de la Imagen Docker
         run: |
          docker pull yesibeth/curso-devsecops:latest

       - name: Despliegue Aplicaion
         run: |
           docker run -p 80:80 --name curso-devsecops -d yesibeth/curso-devsecops:latest

       - name: Sleep
         run: | 
          Start-Sleep -Seconds 30

       - name: OWASP ZAP Scan
         uses: zaproxy/action-baseline@v0.11.0
         with:
           target: 'http://localhost:80/'

   
 
 
   
